server {
    listen 80;
    server_name _;

    error_log  /var/log/nginx/error.log debug;
    access_log /var/log/nginx/access.log;

    # Корневая директория для Nginx
    root /var/www/project/src/public;

    location / {
        root /var/www/project/frontend/dist;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /storage/ {
        alias /var/www/project/src/public/storage/;
    }

    location @laravel {
        root /var/www/project/src/public;
        rewrite ^/(.*)$ /index.php?/$1 last;
    }

    location ~ \.php$ {
        root /var/www/project/src/public;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        
        # МАГИЯ ЗДЕСЬ! Мы передаем путь ТАК, КАК ЕГО ВИДИТ PHP-КОНТЕЙНЕР:
        fastcgi_param SCRIPT_FILENAME /var/www/public$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
